class AddFieldsToEvent < ActiveRecord::Migration
  def change
add_column :events, :Report_to_be_Confidential, :string
add_column :events, :FDM_Event, :string
add_column :events, :Report_Date, :string
add_column :events, :Location_Airport, :string
add_column :events, :Date_the_Event_Occurred, :string
add_column :events, :Location_of_Event_other_than_Airport, :string
add_column :events, :Location_Country, :string
add_column :events, :Event_Category, :string
add_column :events, :Event_Title, :string
add_column :events, :Description_of_IssueEvent, :string
add_column :events, :Other_information_and_suggestions_from_the_reporter, :string
add_column :events, :Any_Operational_Impact, :string
add_column :events, :Pilot_in_Command_Name, :string
add_column :events, :Second_in_Command_Name, :string
add_column :events, :Time_the_Event_Occurred, :string
add_column :events, :Cabin_Crew_Name, :string
add_column :events, :Additional_Crew_Member_Name, :string
add_column :events, :Callsign, :string
add_column :events, :Diversion_Airport, :string
add_column :events, :Did_this_occur_in_flight, :string
add_column :events, :Tail_Number, :string
add_column :events, :Aircraft_Type, :string
add_column :events, :Route_From, :string
add_column :events, :Route_To, :string
add_column :events, :Were_you_the_pilot_flying, :string
add_column :events, :Crew_Position, :string
add_column :events, :Seat_Occupied, :string
add_column :events, :Pilot_Flying, :string
add_column :events, :Pilot_Flying_Seat, :string
add_column :events, :Runway_Used, :string
add_column :events, :Aircraft_Altitude, :string
add_column :events, :FLft_Aircraft_Altitude, :string
add_column :events, :Airspeed_KIAS, :string
add_column :events, :Flight_Phase_at_Start_of_Event, :string
add_column :events, :AC_Weight, :string
add_column :events, :KgLb_AC_Weight, :string
add_column :events, :Type_of_Flight, :string
add_column :events, :Event_Runway_Conditions, :string
add_column :events, :Temperature_C, :string
add_column :events, :Meteorological_Conditions, :string
add_column :events, :Visibility, :string
add_column :events, :Wind_Direction, :string
add_column :events, :Wind_Velocity, :string
add_column :events, :QNH, :string
add_column :events, :Icing, :string
add_column :events, :Turbulence, :string
add_column :events, :Rain, :string
add_column :events, :Thunderstorms, :string
add_column :events, :mSM_Visibility, :string
add_column :events, :Meteorological_Conditions_iv, :string
add_column :events, :Did_the_light_hit_your_eye_directly_or_from_the_side, :string
add_column :events, :Describe_visual_phychological_physical_effects, :string
add_column :events, :Do_you_intend_to_seek_medical_attention, :string
add_column :events, :Duration_of_visual_effects, :string
add_column :events, :Color, :string
add_column :events, :Do_you_feel_you_were_intentionally_tracked, :string
add_column :events, :Duration_of_exposure_seconds, :string
add_column :events, :Elevation_of_the_beam_from_horizontal_degrees, :string
add_column :events, :Light_Source_stationary_or_moving, :string
add_column :events, :Nature_of_Beam_constant_flicker_pulsed, :string
add_column :events, :Position_of_light_source_relative_to_geographical_feature_of_aircraft, :string
add_column :events, :Relative_intensity_flashbulb_headlight_sunlight, :string
add_column :events, :Was_the_beam_visible_prior_to_the_incident, :string
add_column :events, :Where_did_the_light_enter_the_cockpit, :string
add_column :events, :Aircraft_Bank_Angle, :string
add_column :events, :Aircraft_Pitch_Angle, :string
add_column :events, :Heading_Approximate_heading_if_in_turn, :string
add_column :events, :Type_Name_of_approach_or_departure_procedure, :string
add_column :events, :Can_you_estimate_how_far_away_the_light_source_was_from_your_location, :string
add_column :events, :Did_any_of_these_sustain_damage_by_the_light, :string
add_column :events, :Did_anyone_else_see_the_light_beam, :string
add_column :events, :Did_the_light_come_on_suddenly_and_did_it_become_brighter_as_you_approachedit, :string
add_column :events, :Did_the_light_prevent_or_hamper_you_from_doing_those_tasks_or_was_the_light_more_of_an_annoyance, :string
add_column :events, :Did_the_light_seem_to_track_your_path_or_was_there_incidental_contact, :string
add_column :events, :Did_you_attempt_an_evasive_manoeuvre, :string
add_column :events, :Did_you_look_straight_into_the_light_beam_or_off_to_the_side, :string
add_column :events, :Did_you_touch_or_rub_your_eyes_at_the_time_of_the_incident, :string
add_column :events, :How_long_was_the_exposure, :string
add_column :events, :How_successful_were_you_avoiding_it, :string
add_column :events, :How_would_you_describe_the_brightness_of_the_light, :string
add_column :events, :If_it_flickered_how_rapidly_and_regularly, :string
add_column :events, :If_so_did_the_beam_follow_you_as_you_tried_to_move_away, :string
add_column :events, :Was_it_equally_bright_in_all_areas_or_was_it_brighter_in_one_area, :string
add_column :events, :Was_the_light_coming_directly_from_its_source_or_did_it_appear_to_be_reflected_off_other_surface, :string
add_column :events, :Was_the_light_continuous_or_did_it_seem_to_flicker, :string
add_column :events, :Was_the_source_moving, :string
add_column :events, :Were_there_multiple_sources_of_light, :string
add_column :events, :What_tasks_were_you_performing_when_the_exposure_occurred, :string
add_column :events, :What_was_between_the_light_source_and_your_eyes, :string
add_column :events, :Autopilot, :string
add_column :events, :Autothrottle, :string
add_column :events, :Flaps, :string
add_column :events, :Speedbrake, :string
add_column :events, :Spoilers, :string
add_column :events, :Gear, :string
add_column :events, :TCAS_Alert, :string
add_column :events, :Type_of_RA, :string
add_column :events, :Complied_with_RA_Command, :string
add_column :events, :Loss_of_separation, :string
add_column :events, :Direction_of_Traffic_horizontal, :string
add_column :events, :Direction_of_Traffic_vertical, :string
add_column :events, :Aircraft_Vertical_Speed, :string
add_column :events, :Vertical_Deviation, :string
add_column :events, :Reported_to_ATC, :string
add_column :events, :Deviation_detected_by, :string
add_column :events, :What_was_the_rate_of_climb_approachin_the_Cleared_altitude_level, :string
add_column :events, :Thousandft_level_off, :string
add_column :events, :Altitude_capture_mode_armed, :string
add_column :events, :Altitude_captured, :string
add_column :events, :Altitude_selection_confirmed_by_PNF, :string
add_column :events, :Correct_altitude_read_back_by_PNF, :string
add_column :events, :Correct_altitute_set_by_PF, :string
add_column :events, :Type_of_warning, :string
add_column :events, :Did_you_follow_the_EGPWS_procedure, :string
add_column :events, :Vertical_Speed, :string
add_column :events, :Radio_Altimeter, :string
add_column :events, :Errors_Description, :string
add_column :events, :Aircraft_Area_Damaged, :string
add_column :events, :Maintenance_Facility, :string
add_column :events, :Applicable_checklist_performed, :string
add_column :events, :Defect_entry_made_in_Techlog, :string
add_column :events, :Position_on_Glidepath, :string
add_column :events, :Heading, :string
add_column :events, :Altitude_Change, :string
add_column :events, :Change_of_attitude_Pitch, :string
add_column :events, :Change_of_attitude_Roll, :string
add_column :events, :Change_of_attitude_Yaw, :string
add_column :events, :Suspected_ac_visibile, :string
add_column :events, :Suspected_aircraft_type, :string
add_column :events, :Suspected_aircraft_Callsign, :string
add_column :events, :Estimated_Separation_NM, :string
add_column :events, :Stickshaker, :string
add_column :events, :Type_of_Animal, :string
add_column :events, :Number_of_Animals_Seen, :string
add_column :events, :Number_of_Animals_Struck, :string
add_column :events, :Describe_points_of_impact, :string
add_column :events, :Fire, :string
add_column :events, :Sparks, :string
add_column :events, :Smoke, :string
add_column :events, :Fumes, :string
  end
end
